select * from members;
select * from schedule;
select * from diary;
select * from study_time;
select * from score;
select * from board;
select * from comments;
select * from d_day;
select * from memo;